title: <p align="center">Sandhya Girish </p>
logo: /assets/img/Sandhya_Passport Photo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/Sandhya-Girish">GitHub</a>
  
  <br>   
  I'm working in the IT industry from 22 years and working in various 
  leadership roles with a dynamic global experience.
  I have a very good hands-on experience in strategies, roadmaps, 
  Artificial Intelligence & Machine Learning.
  My main strength is active listening and thought leadership.
  <br>
  </p>

theme: jekyll-theme-minimal
